# Generated by Django 5.1.5 on 2025-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="issue_images/"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=15,
            ),
        ),
    ]
