# Generated by Django 5.1.5 on 2025-01-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_issue_image_alter_issue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
