# Generated by Django 5.1.5 on 2025-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_issue_predicted_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="issue",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
