# Generated by Django 5.1.5 on 2025-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_analysis_staff_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="energy_required",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="environmental_impact",
            field=models.IntegerField(
                blank=True, help_text="Environmental impact (0-100)", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="estimated_cost",
            field=models.IntegerField(
                blank=True, help_text="Estimated cost in GBP", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="estimated_time",
            field=models.IntegerField(
                blank=True, help_text="Estimated time to fix in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="priority_level",
            field=models.IntegerField(
                blank=True, help_text="Priority level (1-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="recommended_action",
            field=models.CharField(
                choices=[
                    ("repair", "Repair"),
                    ("replace", "Replace"),
                    ("monitor", "Monitor"),
                    ("refer", "Refer to External Team"),
                ],
                default="repair",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="supporting_document",
            field=models.FileField(blank=True, null=True, upload_to="analysis_docs/"),
        ),
    ]
